### ISSUE TITLE
Allow the Dead Letter Queue to record the original message 

### ISSUE THREAD

**Issue by fpacifici** [getsentry/arroyo#142]
The arroyo DLQ can be applied to any Processing Strategy.
While this is a relatively simple design it does not solve the most common DLQ problem: accumulate invalid messages and replay them after a fix is applied.
This is because only the first transformation step in an Arroyo consumer has access to the original message generally. If an error is identified in a following step, only the partially processed message would be sent to the DLQ, thus making it impossible to replay the messages.

One option would be to leave this in the hands of the application developer and recommend that the original message would be passed through as well. I think this is gross. It would make it really cumbersome and discourage people from employing the DLQ which would be an anti pattern.

Alternative option:
make the DLQ more transparent than it is now. Each step wrapped by a DLQ would only provide offset and partition in the invalid message (or invalid messages) exception. The DLQ step would be wrapping the entire strategy and would keep track of the original message indexed by partition and offset. When the DLQ strategy sees an invalid message it would produce the original message on the DLQ topic. (we would need to figure out a good way to clean up this buffer when offsets are committed)

**Comment by lynnagara** [comment]
Option 3: Rewind the consumer and re-consume the bad message, this time knowing it is bad ahead of time

How it would work:
- The DLQ is not a regular processing strategy but an optional parameter passed to the stream processor
- Any strategy can raise an InvalidMessage with a specific offset (the message body is not required though)
- As soon as the StreamProcessor sees the Invalid Message it terminates the processing strategy and rewinds the consumer back to the last committed offset.
- The consumer then processes all the messages normally but stops at what it now knows is the bad offset
- When it hits the bad offset, it passes it to the DLQ which produces and immediately commits that
- Then it recreates the strategy again and continues normally

From the stream processor's perspective it is a bit of a dance. Throughput will slow temporarily. But it hides the complexity entirely inside the Arroyo library so users don't have to care and the processing strategy interface is dead simple. There is no need to buffer messages or pass copies of them through all the steps.

What do you think?

**Comment by lynnagara** [comment]
We did it
