### ISSUE TITLE
Make arroyo serve a liveness/readiness checks for k8s

### ISSUE THREAD

**Issue by untitaker** [getsentry/arroyo#247]
This idea was provided by @beezz. Arroyo consumers can die because of many reasons. The largest category is about the main thread being blocked. Main thread can be blocked due to bugs during rebalancing (as observed in #217 #237), or because the user-defined strategy (or RunTask) misbehaves.

When we fail to poll, Kafka already kicks us out of the broker after `max.poll.interval`. But the pod is still there, doing nothing.

The suggestion by michal is as follows: We should, everytime we poll, touch a file (debounced). If the file has not been recently touched, k8s notices and deletes the pod.

**Comment by mwarkentin** [comment]
Here are some docs showing how this works from kubernetes side: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

**Comment by untitaker** [comment]
another link from michael: https://danielw.cn/health-check-probes-in-k8s
