### ISSUE TITLE
Filter step should emit metrics about dropped events

### ISSUE THREAD

**Issue by lynnagara** [getsentry/arroyo#257]
Looked into replacing some hand rolled strategies with Filter and other built in Arroyo strategies, and noticed some metrics are missing that are probably useful to end users.

e.g. https://github.com/getsentry/snuba/blob/2705677b817be29abd83b69bedd7bcb379df2234/snuba/subscriptions/executor_consumer.py#L357

The filter step could just automatically record this.

**Comment by ayirr7** [comment]
One question, the linked code obtains the entity name by decoding a scheduled subscription task, and then emits the `skipped_execution` metric with this entity name. Do we want to retain this information if emitting this metric in the FilterStep in Arroyo? I'm not sure how we could obtain it.

**Comment by ayirr7** [comment]
@lynnagara One question, the linked code obtains the entity name by decoding a scheduled subscription task, and then emits the `skipped_execution` metric with this entity name. Do we want to retain this information if emitting this metric in the FilterStep in Arroyo? I'm not sure how we could obtain it.

**Comment by lynnagara** [comment]
No need to explicitly include any tags in here as the metric interface allows the user to configure any custom tags they like when it's initialized. We already attach the storage, consumer group and other information to all arroyo metrics emitted from Snuba.

**Comment by lynnagara** [comment]
Done in https://github.com/getsentry/arroyo/pull/265
